# Generated by Django 6.0.7 on 2026-07-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_arrival_minutes', models.PositiveIntegerField(default=0)),
                ('early_checkout_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('WFH', 'Work From Home'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend')], default='ABSENT', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_payroll_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-attendance_date', 'employee__employee_id'],
                'indexes': [models.Index(fields=['attendance_date'], name='attendance__attenda_9d89bd_idx'), models.Index(fields=['attendance_status'], name='attendance__attenda_94fe3c_idx'), models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_37ed17_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_attendance_per_employee_per_day'), models.CheckConstraint(condition=models.Q(('working_hours__gte', 0)), name='working_hours_non_negative'), models.CheckConstraint(condition=models.Q(('break_hours__gte', 0)), name='break_hours_non_negative'), models.CheckConstraint(condition=models.Q(('overtime_hours__gte', 0)), name='overtime_hours_non_negative'), models.CheckConstraint(condition=models.Q(('check_out_time__isnull', True), ('check_in_time__isnull', True), ('check_out_time__gt', models.F('check_in_time')), _connector='OR'), name='checkout_after_checkin')],
            },
        ),
    ]
